version: '3'
services:
  s10:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S10
      - WEB_VNC=true    
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm
  s9:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6081:6080
      - 5556:5554
      - 5557:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S9
      - WEB_VNC=true    
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm
  s8:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6082:6080
      - 5558:5554
      - 5559:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S8
      - WEB_VNC=true    
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm
  s7:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6083:6080
      - 5560:5554
      - 5561:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S7
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm

  s7-edge:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6084:6080
      - 5562:5554
      - 5563:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S7 Edge
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm      
  s6:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6085:6080
      - 5564:5554
      - 5565:5555
    environment:
      - EMULATOR_DEVICE=Samsung Galaxy S6
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm    
  nexus4:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6086:6080
      - 5566:5554
      - 5567:5555
    environment:
      - EMULATOR_DEVICE=Nexus 4
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm    
  nexus5:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6087:6080
      - 5568:5554
      - 5569:5555
    environment:
      - EMULATOR_DEVICE=Nexus 5
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm
  nexus1:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6088:6080
      - 5570:5554
      - 5571:5555
    environment:
      - EMULATOR_DEVICE=Nexus One
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm 
  nexusS:
    image: budtmo/docker-android:emulator_13.0
    privileged: true
    ports:
      - 6089:6080
      - 5572:5554
      - 5573:5555
    environment:
      - EMULATOR_DEVICE=Nexus S
      - WEB_VNC=true     
    volumes:
      - /home/qauser/mlwallet-android.apk:/home/androidusr/mlwallet-android.apk
    devices:
      - /dev/kvm       
